# Generated by Django 3.1.4 on 2021-07-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cds',
            fields=[
                ('cdsid', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.TextField(max_length=255)),
                ('gbkid', models.TextField(max_length=20)),
                ('geneid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('source', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EnzymeAnnotation',
            fields=[
                ('ec_id', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('enzymeannotationid', models.IntegerField()),
                ('sou_name', models.TextField(max_length=20)),
                ('sou_version', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('geneid', models.IntegerField(primary_key=True, serialize=False)),
                ('transcriptid', models.TextField(max_length=10)),
                ('reg_start', models.IntegerField()),
                ('reg_stop', models.IntegerField()),
                ('strand', models.CharField(max_length=1)),
                ('index', models.IntegerField()),
                ('gc_content', models.TextField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GeneOntology',
            fields=[
                ('gene_ontology_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('defition', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GenomicSequence',
            fields=[
                ('gbkid', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('gbkdefinition', models.TextField()),
                ('length', models.IntegerField()),
                ('mol_type', models.TextField(max_length=32)),
                ('status', models.TextField(max_length=50)),
                ('projectid', models.IntegerField()),
                ('seq_type', models.TextField(max_length=30)),
                ('gc_content', models.IntegerField()),
                ('taxonomy_id', models.IntegerField()),
                ('gbkdivision', models.TextField(max_length=16)),
                ('gi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxRank',
            fields=[
                ('tax_rank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DomainAnnotation',
            fields=[
                ('domain_id', models.ForeignKey(max_length=7, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BioStringProject.domain')),
                ('domainannotationid', models.IntegerField()),
                ('position', models.TextField(max_length=15)),
                ('sou_name', models.TextField(max_length=20)),
                ('sou_version', models.TextField(max_length=10)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GoAnnotation',
            fields=[
                ('gene_ontology_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BioStringProject.geneontology')),
                ('goannotationid', models.IntegerField()),
                ('sou_name', models.TextField(max_length=20)),
                ('sou_version', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Synonymous',
            fields=[
                ('taxonomy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BioStringProject.taxonomy')),
                ('synonimum', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('taxonomy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=256)),
                ('tax_rank_id', models.IntegerField()),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioStringProject.taxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('relationship_id', models.IntegerField(primary_key=True, serialize=False)),
                ('relationship_type', models.IntegerField()),
                ('gene_ontology_id', models.IntegerField()),
                ('chi_gene_ontology_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioStringProject.geneontology')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('proteinid', models.IntegerField()),
                ('gbkid', models.TextField(max_length=15)),
                ('uniprotid', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('length', models.IntegerField()),
                ('definition', models.TextField()),
                ('taxonomy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioStringProject.taxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='OrfT',
            fields=[
                ('orftid', models.IntegerField(primary_key=True, serialize=False)),
                ('length', models.IntegerField()),
                ('taxonomy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioStringProject.taxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='Enzyme',
            fields=[
                ('ec_id', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=150)),
                ('description', models.TextField(max_length=255)),
                ('father', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='BioStringProject.enzyme')),
            ],
        ),
    ]
